/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbChannel */

#ifndef _Included_com_dvb_alitech_DvbProgNodeEdit
#define _Included_com_dvb_alitech_DvbProgNodeEdit
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_dvb_alitech_DvbProgNodeEdit
 * Method:    deleteProg
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbProgNodeEdit_deleteProg
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_dvb_alitech_DvbProgNodeEdit
 * Method:    moveProg
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbProgNodeEdit_moveProg
  (JNIEnv *, jclass, jint ,jint );

/*
 * Class:     com_dvb_alitech_DvbProgNodeEdit
 * Method:    updateData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_DvbProgNodeEdit_updateData
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
